language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false
Env:
  - CODECOV_TOKEN="b9f8cc39-c352-4000-b4f5-dd11d0362ed9"
after_success:
  - if [ -f test/quietly.log ]; then cat test/quietly.log; fi
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate(); 
            Pkg.add("Coverage"); using Coverage;
            Codecov.submit( Codecov.process_folder() );

jobs:
  include:
    - stage: "Additional tests"
      script:
        - julia --project=test/themes -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=test/themes test/themes/themes.jl
      name: "Themes"
    - script:
      - julia --project=test/examples -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); Pkg.add("DocumenterMarkdown")'
      - julia --project=test/examples test/examples/tests_latex.jl
      name: "PDF/LaTeX backend"
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
    - script:
        - julia --project=docs/pdf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/pdf/ docs/pdf/make.jl
      name: "PDF"
      after_success: skip
      services: docker
      codecov: true